# docker-compose -f docker-compose.build.yml build --no-cache
# docker-compose -f docker-compose.build.yml push
version: '3.5'
services:
  dotnetcore-builder:
    image: tjmt/dotnetcore:builder
    build: 
      context: .
      dockerfile: Dockerfile      
      args:
        TimeZone: "America/Cuiaba" #OPCIONAL: default = America/Cuiaba
        SONAR_SCANNER_DOTNET_VERSION: "4.5.0" #OPCIONAL: default = 4.4.2
        COVERLET_CONSOLE_VERSION: "1.3.0" #OPCIONAL: default = 1.2.1
        NUGET_SOURCE_EXTERNO: "https://api.nuget.org/v3/index.json" #OPCIONAL
        NUGET_SOURCE_INTERNO: "http://packages.tjmt.jus.br/nuget/nuget" #OPCIONAL
        HTTP_PROXY: "" #OPCIONAL
        HTTP_PROXY_USER: "" #OPCIONAL
        HTTP_PROXY_PASSWORD: "" #OPCIONAL